function asyncGeneratorStep(H,x,N,I,J,G,E){try{var K=H[G](E),F=K.value}catch(O){N(O);return}K.done?x(F):Promise.resolve(F).then(I,J)}function _asyncToGenerator(H){return function(){var x=this,N=arguments;return new Promise(function(I,J){function G(F){asyncGeneratorStep(K,I,J,G,E,"next",F)}function E(F){asyncGeneratorStep(K,I,J,G,E,"throw",F)}var K=H.apply(x,N);G(void 0)})}}
function _typeof(H){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(x){return typeof x}:function(x){return x&&"function"===typeof Symbol&&x.constructor===Symbol&&x!==Symbol.prototype?"symbol":typeof x};return _typeof(H)}var _regenerator;
(function(){var H=function(x){function N(b,a,c,q){a=Object.create((a&&a.prototype instanceof J?a:J).prototype);q=new P(q||[]);a._invoke=O(b,c,q);return a}function I(b,a,c){try{return{type:"normal",arg:b.call(a,c)}}catch(q){return{type:"throw",arg:q}}}function J(){}function G(){}function E(){}function K(b){["next","throw","return"].forEach(function(a){b[a]=function(c){return this._invoke(a,c)}})}function F(b,a){function c(g,w,v,y){g=I(b[g],b,w);if("throw"===g.type)y(g.arg);else{var A=g.arg;return(g=
A.value)&&"object"===_typeof(g)&&B.call(g,"__await")?a.resolve(g.__await).then(function(z){c("next",z,v,y)},function(z){c("throw",z,v,y)}):a.resolve(g).then(function(z){A.value=z;v(A)},function(z){return c("throw",z,v,y)})}}var q;this._invoke=function(g,w){function v(){return new a(function(y,A){c(g,w,y,A)})}return q=q?q.then(v,v):v()}}function O(b,a,c){var q=m;return function(g,w){if(q===d)throw Error("Generator is already running");if(q===f){if("throw"===g)throw w;return U()}c.method=g;for(c.arg=
w;;){if(g=c.delegate)if(g=S(g,c)){if(g===h)continue;return g}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(q===m)throw q=f,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);q=d;g=I(b,a,c);if("normal"===g.type){q=c.done?f:n;if(g.arg===h)continue;return{value:g.arg,done:c.done}}"throw"===g.type&&(q=f,c.method="throw",c.arg=g.arg)}}}function S(b,a){var c=b.iterator[a.method];if(c===u){a.delegate=null;if("throw"===a.method){if(b.iterator["return"]&&
(a.method="return",a.arg=u,S(b,a),"throw"===a.method))return h;a.method="throw";a.arg=new TypeError("The iterator does not provide a 'throw' method")}return h}c=I(c,b.iterator,a.arg);if("throw"===c.type)return a.method="throw",a.arg=c.arg,a.delegate=null,h;c=c.arg;if(!c)return a.method="throw",a.arg=new TypeError("iterator result is not an object"),a.delegate=null,h;if(c.done)a[b.resultName]=c.value,a.next=b.nextLoc,"return"!==a.method&&(a.method="next",a.arg=u);else return c;a.delegate=null;return h}
function V(b){var a={tryLoc:b[0]};1 in b&&(a.catchLoc=b[1]);2 in b&&(a.finallyLoc=b[2],a.afterLoc=b[3]);this.tryEntries.push(a)}function Q(b){var a=b.completion||{};a.type="normal";delete a.arg;b.completion=a}function P(b){this.tryEntries=[{tryLoc:"root"}];b.forEach(V,this);this.reset(!0)}function R(b){if(b){var a=b[r];if(a)return a.call(b);if("function"===typeof b.next)return b;if(!isNaN(b.length)){var c=-1;a=function g(){for(;++c<b.length;)if(B.call(b,c))return g.value=b[c],g.done=!1,g;g.value=
u;g.done=!0;return g};return a.next=a}}return{next:U}}function U(){return{value:u,done:!0}}var C=Object.prototype,B=C.hasOwnProperty,u,p="function"===typeof Symbol?Symbol:{},r=p.iterator||"@@iterator",l=p.asyncIterator||"@@asyncIterator",k=p.toStringTag||"@@toStringTag";x.wrap=N;var m="suspendedStart",n="suspendedYield",d="executing",f="completed",h={};p={};p[r]=function(){return this};var e=Object.getPrototypeOf;(e=e&&e(e(R([]))))&&e!==C&&B.call(e,r)&&(p=e);var t=E.prototype=J.prototype=Object.create(p);
G.prototype=t.constructor=E;E.constructor=G;E[k]=G.displayName="GeneratorFunction";x.isGeneratorFunction=function(b){return(b="function"===typeof b&&b.constructor)?b===G||"GeneratorFunction"===(b.displayName||b.name):!1};x.mark=function(b){Object.setPrototypeOf?Object.setPrototypeOf(b,E):(b.__proto__=E,k in b||(b[k]="GeneratorFunction"));b.prototype=Object.create(t);return b};x.awrap=function(b){return{__await:b}};K(F.prototype);F.prototype[l]=function(){return this};x.AsyncIterator=F;x.async=function(b,
a,c,q,g){void 0===g&&(g=Promise);var w=new F(N(b,a,c,q),g);return x.isGeneratorFunction(a)?w:w.next().then(function(v){return v.done?v.value:w.next()})};K(t);t[k]="Generator";t[r]=function(){return this};t.toString=function(){return"[object Generator]"};x.keys=function(b){var a=[],c;for(c in b)a.push(c);a.reverse();return function g(){for(;a.length;){var w=a.pop();if(w in b)return g.value=w,g.done=!1,g}g.done=!0;return g}};x.values=R;P.prototype={constructor:P,reset:function(b){this.next=this.prev=
0;this.sent=this._sent=u;this.done=!1;this.delegate=null;this.method="next";this.arg=u;this.tryEntries.forEach(Q);if(!b)for(var a in this)"t"===a.charAt(0)&&B.call(this,a)&&!isNaN(+a.slice(1))&&(this[a]=u)},stop:function(){this.done=!0;var b=this.tryEntries[0].completion;if("throw"===b.type)throw b.arg;return this.rval},dispatchException:function(b){function a(A,z){w.type="throw";w.arg=b;c.next=A;z&&(c.method="next",c.arg=u);return!!z}if(this.done)throw b;for(var c=this,q=this.tryEntries.length-1;0<=
q;--q){var g=this.tryEntries[q],w=g.completion;if("root"===g.tryLoc)return a("end");if(g.tryLoc<=this.prev){var v=B.call(g,"catchLoc"),y=B.call(g,"finallyLoc");if(v&&y){if(this.prev<g.catchLoc)return a(g.catchLoc,!0);if(this.prev<g.finallyLoc)return a(g.finallyLoc)}else if(v){if(this.prev<g.catchLoc)return a(g.catchLoc,!0)}else if(y){if(this.prev<g.finallyLoc)return a(g.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(b,a){for(var c=this.tryEntries.length-
1;0<=c;--c){var q=this.tryEntries[c];if(q.tryLoc<=this.prev&&B.call(q,"finallyLoc")&&this.prev<q.finallyLoc){var g=q;break}}g&&("break"===b||"continue"===b)&&g.tryLoc<=a&&a<=g.finallyLoc&&(g=null);c=g?g.completion:{};c.type=b;c.arg=a;return g?(this.method="next",this.next=g.finallyLoc,h):this.complete(c)},complete:function(b,a){if("throw"===b.type)throw b.arg;"break"===b.type||"continue"===b.type?this.next=b.arg:"return"===b.type?(this.rval=this.arg=b.arg,this.method="return",this.next="end"):"normal"===
b.type&&a&&(this.next=a);return h},finish:function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.finallyLoc===b)return this.complete(c.completion,c.afterLoc),Q(c),h}},"catch":function(b){for(var a=this.tryEntries.length-1;0<=a;--a){var c=this.tryEntries[a];if(c.tryLoc===b){b=c.completion;if("throw"===b.type){var q=b.arg;Q(c)}return q}}throw Error("illegal catch attempt");},delegateYield:function(b,a,c){this.delegate={iterator:R(b),resultName:a,nextLoc:c};"next"===this.method&&
(this.arg=u);return h}};return x}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=H}catch(x){Function("r","_regenerator = r")(H)}})();
(function(){function H(){H=_asyncToGenerator(_regenerator.mark(function r(p){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return jQuery(p).attr("disabled",!0),l.prev=1,l.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:l.next=8;break;case 6:l.prev=6,l.t0=l["catch"](1);case 8:jQuery(p).attr("disabled",!1);case 9:case "end":return l.stop()}},r,this,[[1,6]])}));
return H.apply(this,arguments)}function x(){x=_asyncToGenerator(_regenerator.mark(function l(p,r){var k,m,n,d,f,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:k=jQuery(p.parentNode).closest(".blck").first();m=k.find(".seraph_accel_spinner");k.find(".content");n=k.find('input[type="button"]:not(.cancel)');d=k.find('input[type="button"].cancel');if(!r){e.next=23;break}n.prop("disabled",!0);m.show();seraph_accel.Manager._int.notRefreshStat=!0;f=null;e.prev=10;e.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(f=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=20;break;case 17:e.prev=17,e.t0=e["catch"](10),f="HTTP "+e.t0.status;case 20:return f&&(alert(f),n.prop("disabled",!1),m.hide()),delete seraph_accel.Manager._int.notRefreshStat,e.abrupt("return");case 23:return d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,f=null,e.prev=26,e.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(f=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=37;break;case 33:e.prev=33,e.t1=e["catch"](26),f="HTTP "+e.t1.status,d.prop("disabled",!1);case 37:f&&alert(f),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return e.stop()}},l,this,[[10,17],[26,33]])}));return x.apply(this,arguments)}function N(u){switch(u){case 0:return C("OpDescr_Invalidate",
"admin.Manage","seraphinite-accelerator");case 3:return C("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return C("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return C("OpDescr_SrvDel","admin.Manage","seraphinite-accelerator")}return""+u}function I(){I=_asyncToGenerator(_regenerator.mark(function r(p){var l,k,m,n;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),k=l.find('input[type="button"].cancel'),
k.prop("disabled",!0),m=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:n=d.sent;seraph_accel.Gen.hr.Fail(n)&&(m=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),n));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),m="HTTP "+d.t0.status;case 14:m&&alert(m);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return I.apply(this,arguments)}function J(){J=
_asyncToGenerator(_regenerator.mark(function r(p){var l,k,m,n;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),k=l.find('input[type="button"].cancel'),k.prop("disabled",!0),m=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:n=d.sent;seraph_accel.Gen.hr.Fail(n)&&(m=B(C("OpSrvErr_%1$08X",
"admin.Manage","seraphinite-accelerator"),n));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),m="HTTP "+d.t0.status;case 14:m&&alert(m);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return J.apply(this,arguments)}function G(){G=_asyncToGenerator(_regenerator.mark(function r(p){var l,k,m,n,d,f;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),k=l.find(".seraph_accel_spinner"),m=l.find('input[type="button"]:not(.cancel)'),
n=l.find('input[type="button"].cancel'),k.show(),m.prop("disabled",!0),n.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,d=null,h.prev=9,h.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:f=h.sent;seraph_accel.Gen.hr.Fail(f)&&(d=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),f));h.next=19;break;case 16:h.prev=16,h.t0=h["catch"](9),d="HTTP "+h.t0.status;
case 19:d&&alert(d),delete seraph_accel.Manager._int.notRefreshExtDp;case 21:case "end":return h.stop()}},r,this,[[9,16]])}));return G.apply(this,arguments)}function E(){E=_asyncToGenerator(_regenerator.mark(function r(p){var l,k,m,n;return _regenerator.wrap(function(d){for(;;)switch(d.prev=d.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),k=l.find('input[type="button"].cancel'),k.prop("disabled",!0),m=null,d.prev=4,d.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ExtDbUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:n=d.sent;seraph_accel.Gen.hr.Fail(n)&&(m=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),n));d.next=14;break;case 11:d.prev=11,d.t0=d["catch"](4),m="HTTP "+d.t0.status;case 14:m&&alert(m);case 15:case "end":return d.stop()}},r,this,[[4,11]])}));return E.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function l(p,r){var k,m,n,d,f,h,e,t,b,a,c,q,g,w;return _regenerator.wrap(function(v){for(;;)switch(v.prev=
v.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),m=k.find(".seraph_accel_spinner"),n=k.find(".descr"),d=k.find('input[type="button"]:not(.cancel)'),f=k.find('input[type="button"].cancel'),h=k.find("#seraph_accel_views"),e=k.find("#seraph_accel_geos"),t=[],h.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(h.get()),t=seraph_accel.Ui.TokensList.GetVal(h.get())),b=[],e.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(e.get()),b=seraph_accel.Ui.TokensList.GetVal(e.get())),c=String(k.find(".type").val()),
"uri"===c?a=k.find(".uri").val():0===c.indexOf("uri:")&&(a=c.substr(4),c="uri"),a=seraph_accel.Gen.StrReplaceAll(String(a),["\r","\n","*"],["",";","{ASTRSK}"]),m.show(),n.show(),n.text(N(r)),d.prop("disabled",!0),f.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,q={cache:!1,dataType:"json"},512>a.length?q.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:c,op:r,uri:a,v:t.join(),g:b.length?b.join():void 0}):(q.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"CacheOpBegin",{type:c,op:r,v:t.join(),g:b.length?b.join():void 0}),q.type="POST",q.contentType="application/x-www-form-urlencoded",q.data="uri="+encodeURIComponent(a)),g=null,v.prev=23,v.next=26,jQuery.ajax(q);case 26:w=v.sent;seraph_accel.Gen.hr.Fail(w)&&(g=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),w));v.next=33;break;case 30:v.prev=30,v.t0=v["catch"](23),g="HTTP "+v.t0.status;case 33:g&&alert(g),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return v.stop()}},
l,this,[[23,30]])}));return K.apply(this,arguments)}function F(){F=_asyncToGenerator(_regenerator.mark(function l(p,r){var k,m,n,d;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),m=k.find('input[type="button"].cancel'),m.prop("disabled",!0),n=null,f.prev=4,f.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:r}),type:"POST",data:"",cache:!1,dataType:"json"});
case 7:d=f.sent;seraph_accel.Gen.hr.Fail(d)&&(n=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),d));f.next=14;break;case 11:f.prev=11,f.t0=f["catch"](4),n="HTTP "+f.t0.status;case 14:n&&alert(n);case 15:case "end":return f.stop()}},l,this,[[4,11]])}));return F.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function k(p,r,l){var m,n,d,f,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return m=jQuery(p.parentNode).closest(".blck").first(),
n=m.find(".seraph_accel_spinner"),d=m.find('input[type="button"]'),n.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,f=null,e.prev=7,e.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueueDelete",{allSites:r?!0:void 0,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 10:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(f=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=17;break;case 14:e.prev=14,
e.t0=e["catch"](7),f="HTTP "+e.t0.status;case 17:f&&(alert(f),n.hide(),d.prop("disabled",!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return e.stop()}},k,this,[[7,14]])}));return O.apply(this,arguments)}function S(){S=_asyncToGenerator(_regenerator.mark(function k(p,r,l){var m,n,d,f,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return m=jQuery(p.parentNode).closest(".blck").first(),n=m.find(".seraph_accel_spinner"),d=m.find('input[type="button"]'),
n.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,f=null,e.prev=7,e.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueuePause",{v:r,_wpnonce:l}),type:"POST",cache:!1,dataType:"json"});case 10:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(f=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=17;break;case 14:e.prev=14,e.t0=e["catch"](7),f="HTTP "+e.t0.status;case 17:f&&(alert(f),n.hide(),d.prop("disabled",
!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return e.stop()}},k,this,[[7,14]])}));return S.apply(this,arguments)}function V(){V=_asyncToGenerator(_regenerator.mark(function k(p,r,l){var m,n,d,f,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:if(confirm(C("ItemCancelConfirm","admin.Manage_Queue","seraphinite-accelerator"))){e.next=2;break}return e.abrupt("return");case 2:return m=jQuery(p.parentNode).closest(".blck").first(),n=m.find(".seraph_accel_spinner"),
d=m.find('input[type="button"]'),n.show(),d.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,f=null,e.prev=9,e.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueueItemCancel",{pc:r,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 12:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(f=B(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=19;break;case 16:e.prev=16,e.t0=e["catch"](9),f="HTTP "+e.t0.status;case 19:f&&
alert(f),n.hide(),d.prop("disabled",!1),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 23:case "end":return e.stop()}},k,this,[[9,16]])}));return V.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function l(p,r){var k,m,n,d;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:d=function(){d=_asyncToGenerator(_regenerator.mark(function e(){return _regenerator.wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return t.next=2,seraph_accel.Manager._int.OnDataRefresh(p,
r);case 2:m();case 3:case "end":return t.stop()}},e,this)}));return d.apply(this,arguments)},n=function(){return d.apply(this,arguments)},m=function(){var h=1E3*parseInt(k.val(),10);100>h&&(h=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);seraph_accel.Manager._int.refreshTimer=setTimeout(n,h)},k=jQuery(p).find("#queue .tmDataRefresh"),k.on("change",m),n();case 6:case "end":return f.stop()}},l,this)}));return Q.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function l(p,
r){var k,m,n,d,f,h,e,t,b,a,c,q,g,w,v,y,A,z,L,D,T;return _regenerator.wrap(function(M){for(;;)switch(M.prev=M.next){case 0:return k=jQuery(p).find("#status").first(),m=jQuery(p).find("#stat").first(),n=m.find(".seraph_accel_spinner"),d=m.find('input[type="button"]:not(.cancel)'),f=m.find('input[type="button"].cancel'),h=jQuery(p).find("#operate").first(),e=h.find(".seraph_accel_spinner"),t=h.find(".descr"),b=h.find('input[type="button"]:not(.cancel)'),a=h.find('input[type="button"].cancel'),c=jQuery(p).find("#queue").first(),
q=c.find(".content"),g=c.find(".maxItems"),w=c.find(".seraph_accel_spinner"),v=c.find('input[type="button"]'),y=c.find(".descrNums"),M.prev=16,M.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",{nMaxQueueItems:g.val(),allSites:r?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:D=M.sent;M.next=24;break;case 22:M.prev=22,M.t0=M["catch"](16);case 24:if(D){M.next=26;break}return M.abrupt("return");case 26:if(!r){for(T in D.status.cont)k.find('[data-id-cont="'+
T+'"]').html(D.status.cont[T]);seraph_accel.Manager._int.notRefreshPostUpd||(A=k.find(".blck.postupd .seraph_accel_spinner"),z=k.find('.blck.postupd input[type="button"]:not(.cancel)'),L=k.find('.blck.postupd input[type="button"].cancel'),D.status.postUpd?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(A=k.find(".blck.scheupd .seraph_accel_spinner"),z=k.find('.blck.scheupd input[type="button"]:not(.cancel)'),
L=k.find('.blck.scheupd input[type="button"].cancel'),D.status.scheUpd?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||(A=k.find(".blck.cleanup .seraph_accel_spinner"),z=k.find('.blck.cleanup input[type="button"]:not(.cancel)'),L=k.find('.blck.cleanup input[type="button"].cancel'),D.status.cleanUp?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",
!0)))}r||seraph_accel.Manager._int.notRefreshExtDp||(A=k.find(".blck.extdb .seraph_accel_spinner"),z=k.find('.blck.extdb input[type="button"]:not(.cancel)'),L=k.find('.blck.extdb input[type="button"].cancel'),D.extDb.isUpdating?(A.show(),z.prop("disabled",!0),L.prop("disabled",!1)):(A.hide(),z.prop("disabled",!1),L.prop("disabled",!0)));if(!r&&!seraph_accel.Manager._int.notRefreshStat)for(T in D.stat.isUpdating?(n.show(),d.prop("disabled",!0),f.prop("disabled",!1)):(n.hide(),d.prop("disabled",!1),
f.prop("disabled",!0)),D.stat.cont)m.find('[data-id-cont="'+T+'"]').html(D.stat.cont[T]);r||seraph_accel.Manager._int.notRefreshOp||(null===D.curOp&&(D.curOp=void 0),void 0!==D.curOp?(e.show(),t.show(),t.text(N(D.curOp)),b.prop("disabled",!0),a.prop("disabled",!1)):(e.hide(),t.hide(),b.prop("disabled",!1),a.prop("disabled",!0),t.text("")));q.html(D.queue.content);y.text(B(C("QueueNumsDescr_%1$u%2$u","admin.Manage","seraphinite-accelerator"),D.queue.nums.nInitial,D.queue.nums.nInProgress));seraph_accel.Manager._int.notRefreshQueueDeleting||
(w.hide(),v.prop("disabled",!1),D.queue.isPaused?(c.find('input[type="button"].pause').hide(),c.find('input[type="button"].resume').show()):(c.find('input[type="button"].pause').show(),c.find('input[type="button"].resume').hide()));case 33:case "end":return M.stop()}},l,this,[[16,22]])}));return P.apply(this,arguments)}function R(){R=_asyncToGenerator(_regenerator.mark(function r(p){var l,k,m,n,d,f,h,e;return _regenerator.wrap(function(t){for(;;)switch(t.prev=t.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),
k=l.find(".url"),m=l.find(".messages"),n=l.find(".seraph_accel_spinner"),d=l.find('input[type="button"]'),f=0,l.find(".liteChk").prop("checked")&&(f|=1),l.find(".medChk").prop("checked")&&(f|=2),l.find(".tidyChk").prop("checked")&&(f|=524288),m.empty(),n.show(),d.prop("disabled",!0),t.prev=12,t.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:k.val(),norm:f}),type:"POST",data:"",dataType:"json",cache:!1});case 15:h=t.sent;t.next=21;break;
case 18:t.prev=18,t.t0=t["catch"](12),h={err:t.t0.statusText};case 21:n.hide();d.prop("disabled",!1);if(!h.err){t.next=26;break}m.append(seraph_accel.Ui.LogItem("error",h.err));return t.abrupt("return");case 26:for(e in h.list)e=h.list[e],m.append(seraph_accel.Ui.LogItem(e.severity,e.text));case 27:case "end":return t.stop()}},r,this,[[12,18]])}));return R.apply(this,arguments)}var U=seraph_accel.Wp.Loc.GetApi(),C=U._x,B=U.sprintf;seraph_accel.Settings={_int:{StrItem_OnAdd:function(u){function p(m){(m=
m.trim())&&seraph_accel.Ui.TokensList.AddItem(k[0],m)}var r=1<arguments.length&&void 0!==arguments[1]?arguments[1]:",",l=jQuery(u.parentNode).closest(".blck").first(),k=l.find(".vals");l=l.find(".val");r?l.val().split(r).forEach(p):p(l.val());l.val("")},StrItem_OnCopyAll:function(u){seraph_accel.Ui.TokensList.CopyAllItems(jQuery(u.parentNode).closest(".blck").first().find(".vals")[0])},StrItem_OnDelAll:function(u){seraph_accel.Ui.TokensList.DelAllItems(jQuery(u.parentNode).closest(".blck").first().find(".vals")[0])},
OnUpdateCssAuto:function(u){seraph_accel.Ui.ComboShowDependedItems(u,jQuery(u.parentNode).closest(".blck").first().get(0))},OnLogClear:function(u){return H.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(u,p){return x.apply(this,arguments)},OnCacheOp:function(u,p){return K.apply(this,arguments)},OnCacheOpCancel:function(u,p){return F.apply(this,arguments)},OnPostUpdCancel:function(u){return I.apply(this,arguments)},OnScheUpdCancel:function(u){return J.apply(this,arguments)},
OnExtDbUpdBegin:function(u){return G.apply(this,arguments)},OnExtDbUpdCancel:function(u){return E.apply(this,arguments)},OnQueueDel:function(u,p,r){return O.apply(this,arguments)},OnQueuePause:function(u,p,r){return S.apply(this,arguments)},OnQueueItemCancel:function(u,p,r){return V.apply(this,arguments)},OnDataRefreshInit:function(u,p){return Q.apply(this,arguments)},OnDataRefresh:function(u,p){return P.apply(this,arguments)},OnHtmlCheck:function(u){return R.apply(this,arguments)}}};(function(){function u(k){return p.apply(this,
arguments)}function p(){p=_asyncToGenerator(_regenerator.mark(function n(m){var d,f;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return d={},h.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+m,{}),cache:!1,dataType:"json"}),h.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:d=h.sent;delete seraph_accel.SelfDiag._int.curAjax;h.next=14;break;case 9:h.prev=9,h.t0=h["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,
0===h.t0.status?d.hr=seraph_accel.Gen.hr.S_ABORTED:(d.hr=seraph_accel.Gen.hr.E_FAIL,d.descr="HTTP "+h.t0.status),500==h.t0.status&&(f=document.implementation.createHTMLDocument(""),f.documentElement.innerHTML=h.t0.responseText,f=f.body.textContent,f=seraph_accel.Gen.StrReplaceAll(f,"\r",""),f=seraph_accel.Gen.StrReplaceAll(f,["\t","\v"]," "),f=seraph_accel.Gen.StrReplaceAll(f,"\n",". "),(f=seraph_accel.Gen.StrReplaceAllWhileChanging(f,["  ",". . "],[" ",". "]).trim())&&"."!=f&&(d.descr+="<br>"+f));
case 14:return h.abrupt("return",d);case 15:case "end":return h.stop()}},n,this,[[1,9]])}));return p.apply(this,arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function n(m){var d,f,h,e,t,b,a,c,q,g,w,v=arguments;return _regenerator.wrap(function(y){for(;;)switch(y.prev=y.next){case 0:d=1<v.length&&void 0!==v[1]?v[1]:!1;f=jQuery(m.parentNode).closest(".blck").first();h=f.find(".seraph_accel_spinner");e=f.find('input[type="button"]:not(.cancel)');t=f.find('input[type="button"].cancel');
b=f.find(".log");a=[{id:"3rdPartySettCompat",name:l("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},{id:"AsyncRequest",name:l("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:l("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:l("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:l("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},
{id:"ExtCache",name:l("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];b.empty();for(c=0;c<a.length;c++)q=a[c],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",q.name?q.name:q.id),!1));if(!d){y.next=11;break}return y.abrupt("return");case 11:h.show(),e.prop("disabled",!0),t.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,c=0;case 16:if(!(c<a.length)){y.next=31;break}q=a[c];jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",
q.name?q.name:q.id)+l("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));y.next=21;return u(q.id);case 21:g=y.sent;w=l("TestSucc","admin.SelfDiag","seraphinite-accelerator");g.hr!=seraph_accel.Gen.hr.S_OK&&(w=seraph_accel.Gen.hr.Succ(g.hr)?g.hr==seraph_accel.Gen.hr.S_ABORTED?l("TestAbort","admin.SelfDiag","seraphinite-accelerator"):g.hr==seraph_accel.Gen.hr.S_FALSE?l("TestNotice","admin.SelfDiag","seraphinite-accelerator"):l("TestWarn","admin.SelfDiag","seraphinite-accelerator"):l("TestError",
"admin.SelfDiag","seraphinite-accelerator"));g.descr&&(w+="<br>"+g.descr);jQuery(b.children().get(c)).replaceWith(seraph_accel.Ui.LogItem(g.hr==seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(g.hr)?g.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",q.name?q.name:q.id)+w,!1));if(seraph_accel.SelfDiag._int.inProgress){y.next=28;break}return y.abrupt("break",31);case 28:c++;y.next=16;break;case 31:h.hide(),e.prop("disabled",!1),t.prop("disabled",!0);
case 34:case "end":return y.stop()}},n,this)}));return r.apply(this,arguments)}var l=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(k){return r.apply(this,arguments)},OnCancel:function(k){k=jQuery(k.parentNode).closest(".blck").first();k.find(".seraph_accel_spinner");k.find('input[type="button"]:not(.cancel)');k.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},
inProgress:!1}}})()})();
